algoritmo "Exercicio 3-1"

var
//1 - Crie um algoritmo que receba suas informações (pelo menos nome, idade, e curso atual), e exiba na tela.
nome: caractere
idade: inteiro
cursoAtual: caractere

inicio

Escreval("Digite seu nome: ")
leia (nome)
Escreval("Digite sua idade: ")
leia (idade)
Escreval("Digite seu ceurso atual: ")
leia (cursoAtual)

Escreval("------------------------------")

Escreval("Nome: ",nome)
Escreval("Idade: ",idade)
Escreval("Curso Atual: ",cursoAtual)


fimalgoritmo